controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    mecanum_drive_controller:
      type: mecanum_drive_controller/MecanumDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


mecanum_drive_controller:
  ros__parameters:

    publish_rate: 30.0

    command_joint_names: ["front_left_joint", "rear_left_joint", "rear_right_joint", "front_right_joint"]

    interface_name: velocity

    kinematics:
        wheels_radius: 0.4
        sum_of_robot_center_projection_on_X_Y_axis: 1.0

    base_frame_id: "base_link"
    odom_frame_id: "odom"

    enable_odom_tf: true

    use_stamped_vel: true
